- name: Build brcm_patchram_plus (ARMv7)
  shell: bash
  run: |
    set -e
    export NDK="$ANDROID_NDK_HOME"
    export TOOL="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin"
    mkdir -p build
    "$TOOL/clang" --target=armv7a-linux-androideabi16 \
      --sysroot="$NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot" \
      -O2 -Wl,--hash-style=both \
      -o build/brcm_patchram_plus src/*.c
    file build/brcm_patchram_plus || true

- name: Upload artifact
  uses: actions/upload-artifact@v4
  with:
    name: brcm_patchram_plus-armv7-android
    path: build/brcm_patchram_plus
